### PR TITLE
Fix: User logged in status is cached after signing out

### LINKED ISSUE #2409: User logged in status is cached
### Description

When user signs out analytics events continue to report `"user_is_logged_in":true` until the device is restarted. I'm marking this as an analytics bug but this very well may impact other areas of the app relying on logged in status.

### Step-by-step reproduction instructions

1. Open the app.
2. Go to your account.
3. Sign out.
4. Do some stuff.
5. Notice in the logs that analytics report this property `"user_is_logged_in":true`.
6. Close and reopen the app.
7. `user_is_logged_in` property should be now `false`.

### Screenshots or screen recording

_No response_

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 6, Android 14, 7b667c2a683367d0aa4a2b9237dbbd44db60de23

### PR DESCRIPTION
**Pull request by mebarbosa**
## Description
- The logged in status was being persisted because the ` accountManager.removeAccountExplicitly(account)` was not being executed due to the order in which the tasks inside the `action` block were being executed. To ensure that all tasks were executed sequentially, I wrapped them in a coroutine

Fixes #2409

### App
1. Log in with some account
2. Do some stuff to track events
3. ✅ Ensure you see the property `"user_is_logged_in":true`
4. Sign out and don't close the app
5. Do some stuff to track events
6. ✅ Ensure you see the property `"user_is_logged_in":false`

### Watch
- Smoke test sign out

### Automotive
- I noticed the sign out button is not working when I was about to do regression tests for automotive. I am going to create an issue for that

## Checklist
- [x] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [x] Any jetpack compose components I added or changed are covered by compose previews
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.

### CODE REVIEW

File: modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AccountStatusInfo.kt [hunk 1]
```diff
@@ -3,4 +3,5 @@ package au.com.shiftyjelly.pocketcasts.analytics
 interface AccountStatusInfo {
     fun isLoggedIn(): Boolean
     fun getUuid(): String?
+    fun signOut()
```
Comment (MiSikora) [inline modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AccountStatusInfo.kt:6]: This should be handled inside `SyncManagerImpl`. `AccountStatusInfo` is a simple data structure for analytics.

**Review by MiSikora — COMMENTED** [review]
Works as expected. I left one comment though about mixed responsibility.

File: modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AccountStatusInfo.kt (hunk 1 above)
Comment (mebarbosa) [reply modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AccountStatusInfo.kt:6]: I was thinking about this because none of them was fitting for this in my opinion. `SyncManager` reminds me synchronization things and `AccountStatusInfo` reminds me account things, but I also think it's not ideal because of the `*StatusInfo` in the end.

I can move it to `SyncManager`. It's not a big deal

Comment (MiSikora) [reply modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AccountStatusInfo.kt:6]: Looking at the code further it should probably be `SyncAccountManagerImpl` that handles it.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/65">7.74</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AccountStatusInfo.kt (hunk 1 above)
Comment (mebarbosa) [reply modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AccountStatusInfo.kt]: When I was about to move the code, I noticed that `syncAccountManager.signOut()` was already performing this task but wasn't working due to the order in which the tasks inside the `action` block were being executed. To ensure that all tasks were executed sequentially, I wrapped them in a coroutine, and it worked as expected.

I did some regressions tests, but I would like to ask if you do the same if you can.

Comment (mebarbosa) [reply modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AccountStatusInfo.kt]: I removed the unit tests from here since it was not related to this change anymore and added in another PR https://github.com/Automattic/pocket-casts-android/pull/2957

**Review by MiSikora — APPROVED** [review]

File: modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/AccountManagerStatusInfo.kt [hunk 2]
```diff
@@ -1,10 +1,8 @@
 package au.com.shiftyjelly.pocketcasts.repositories.sync
-
 import android.accounts.AccountManager
 import au.com.shiftyjelly.pocketcasts.analytics.AccountStatusInfo
 import au.com.shiftyjelly.pocketcasts.preferences.AccountConstants
 import javax.inject.Inject
-
```
Comment (MiSikora) [inline modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/AccountManagerStatusInfo.kt:7]: These empty spaces shouldn't be removed. Formatting now looks a bit awkward.

File: modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AccountStatusInfo.kt (hunk 1 above)
Comment (MiSikora) [reply modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AccountStatusInfo.kt]: Works as expected. Thanks!
