### PR TITLE
Fix: Subscribe to a podcast makes the page jumps after a few seconds

### LINKED ISSUE #2199: Subscribe to a podcast makes the page jumps after a few seconds
### Description

When you subscribe to a podcast from podcast list filtered by a category you get some small jumps to top

### Step-by-step reproduction instructions

1. Go to Discover
2. Tap on any category
3. Scroll to the middle / bottom of the list
4. Subscribe to a podcast
5. ❌ You will see the jump

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/42220351/63c5d3a6-1dcc-426e-a1e2-cf336c98ba81

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

_No response_

### PR DESCRIPTION
**Pull request by mebarbosa**
## Description
- This PR fixes the pages jumps issue when you subscribe to a podcast from the filtered podcasts list
- While I was working on this issue I also noticed the most popular section had the same problem, so I addressed to this PR

Fixes #2199

## Testing Instructions
1. Go to Discover
2. Filter a category
3. Subscribe to any podcast from Most Popular in [category] section
4. ✅ Ensure the list does not "jump"
5. Go to the remaining category list and scroll a bit
6. Try to subscribe to any podcast from this section
7. ✅ Ensure the list does not "jump"

## Screenshots or Screencast 
[Screen_recording_20240514_080806.webm](https://github.com/Automattic/pocket-casts-android/assets/42220351/193f6503-0747-4816-8771-983091ff370f)

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [ ] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

File: modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/MostPopularPodcastsAdapter.kt [hunk 1]
```diff
@@ -85,20 +84,25 @@ internal class MostPopularPodcastsAdapter(
...
-        if (podcast is DiscoverPodcast) {
-            holder.bind(podcast)
-        }
+    override fun onBindViewHolder(holder: MostPopularPodcastsViewHolder, position: Int) {
+        holder.bind(getItem(position))
     }
+
     fun replaceList(list: List<DiscoverPodcast>) {
-        submitList(null) // We need this to avoid displaying the previous category list when switching from a different category
+        val changedPodcastList = currentList.map { it.uuid } != list.map { it.uuid }
```
Comment (mebarbosa) [inline modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/MostPopularPodcastsAdapter.kt:93]: I tried to use `PODCASTS_FILTERED_DIFF` instead of checking here, but it did not work

**Review by MiSikora — APPROVED** [review]
I can confirm that the page doesn't jump. I think I discovered unrelated performance issues. We drop frames after subscribing to a podcast. You can test it this way:

1. Select a category.
2. Scroll down to the bottom.
3. Subscribe to a podcast and start scrolling to the top.
4. List will stop scrolling at some point.

You can see dropped frames in this video.

https://github.com/Automattic/pocket-casts-android/assets/30936061/0c7f1561-23b4-40b6-8623-c0a43da7e6b3

**Comment by mebarbosa** [comment]
> I can confirm that the page doesn't jump. I think I discovered unrelated performance issues. We drop frames after subscribing to a podcast. You can test it this way:
> 
> 1. Select a category.
> 2. Scroll down to the bottom.
> 3. Subscribe to a podcast and start scrolling to the top.
> 4. List will stop scrolling at some point.
> 
> You can see dropped frames in this video.
> 
>  screen-20240514-153641.mp4

@MiSikora Thanks! I _think_ this might be related to the numbers of `disposables` in discover and the way we track subscriptions status. I need to investigate deeper to confirm this
