### PR TITLE
Avoid race conditions with media command events

### LINKED ISSUE #1578: Pixel headphones double/triple tapping to go forward/back does not work
### Description

It doesn't seem that double/triple tapping to go forward and backward works like it should (at least on Pixel phones). I did some testing of that functionality on different phones and different apps to see where it worked/didn't-work and this is what I found.

|                  | Pixel 8 | Samsung A13 |
|---------------- | --------- | -------------|
| Pocket Casts ⏩  |   ❌    |     🟢      |
| Pocket Casts ⏪️️  |   ❌*    |     ❌      |
| YouTube Music ⏩️️ |   🟢    |     🟢      |
| YouTube Music ⏪️️ |   🟢    |     🟢      |
| Spotify ⏩️️       |   🟢    |     ❌      |
| Spotify ⏪️️       |   🟢    |     ❌      |
| Castbox ⏩       |   🟢    |     ❌      |
| Castbox ⏪       |   🟢    |     ❌      |
| Podbean ⏩       |   🟢    |     ❌      |
| Podbean ⏪       |   🟢    |     ❌      |

* I did notice that with Pocket Casts I would occasionally get a skip back to work, particularly if I just tapped the button a ton of times, but it basically never happened with normal use. It also looked like the playback might be updating it's position and then immediately jumped back to the previous playback position. If that's the case, we might be dealing with a race condition.

We do have some reports of this functionality working fine with Pixel Buds too, so not sure why it's working for some people and not others.

#### References
* [Pocket Casts Forums - Skip function from Bluetooth device not working properly – Beta 7.52-rc-2 (9162)](https://forums.pocketcasts.com/forums/topic/skip-function-from-bluetooth-device-not-working-properly-beta-7-52-rc-2-9162/?view=all#post-2099)
* 7382261-zd-a8c
* 7353758-zd-a8c

### Step-by-step reproduction instructions

1. Play an episode on pocket casts
2. Connect a pair of Pixel headphones (I was using wired, but we have quite a few reports from users having the issue with Bluetooth pixel buds)
3. Double tap to go forward
4. Observe the the audio pauses and unpauses but the playback position does not change
5. Triple tap to go backwards
6. 4. Observe the the audio pauses and unpauses but the playback position does not change

### Screenshots or screen recording

_No response_

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung A13, Android 13, Pocket Casts 7.53 pre-release build
Pixel 8, Android 14, Pocket Casts 7.52-rc-4

### PR DESCRIPTION
**Pull request by mchowning**
## Description
This PR addresses a problem with the skip-forward and skip-back functionality on pixel buds, and fixes #1578.=

I think this is only an issue if the earbuds are [set up to use Google Assistant](https://support.google.com/assistant/answer/9027902?hl=en). At least that's what I've observed when using my usb-c pixel buds which can be used without Google Assistant integration because I only see the issue when the Google Assistant integration is enabled).

I don't have Bluetooth pixel buds to test this, but we have quite a few users reporting this issue with the Bluetooth pixel buds as well. This issue does not appear to occur with regular Bluetooth headphones/speakers in my testing.

I believe this issue is caused by the fact that many of our playback functions in the playback manager launch coroutines for their work, which allows commands that happen in a quick sequence to "overlap" and have race conditions (i.e., the first command is still finishing when the second command starts). When the issue occurs you can see the playback scrubber briefly jumps to the appropriate position and then quickly bounces back to the position before it was at before the skip command, which is why it seems like the skip command isn't working.

To avoid this, I am creating a command queue that all media events send the relevant commands to. This command queue executes the commands one at a time. In addition, I have created suspended versions of the relevant `PlaybackManager` methods that do not launch new coroutines (although the `PlaybackManager` diff looks large, the only change is really to create suspended versions of the methods that already existed). This helps us complete one command before the next command is run. 

There are still a number of other places in the `PlaybackManager` where we are launching new coroutines, and I think that we should also be migrating these to be suspended methods (with rare exceptions, I don't think the PlaybackManager should be launching coroutines, that should be handled classes that are calling the `PlaybackManager` methods).

I have not found a way to consistently recreate this issue (among the things I've tried are hardcoding playback commands and sending media events with adb, but nothing seems to work). The issue does seem to occur a bit more consistently for me with skipping back compared to skipping forward, but it's never been perfectly reproducible for me and other users have reported it suddenly start/stop working as well.

I isolated that the issue got significantly worse after the changes in #1510. The reason for that is likely because it changed the timing of when we fetch the playback position when playing a podcast, and that made us more susceptible to the race condition. I didn't take the approach of reverting that change because it was fixing a bug and the better approach (imo) is avoiding the race condition entirely, which is what this PR is trying to do.

This issue does seem to come and go a bit for me, which is not too surprising since it is a race condition. My suspicion is that this issue has been possible for a long time, but it the changes in #1510 just made it occur far more frequency with Pixel Buds that are using Google assistant.

<details><summary>Some more detail about what is happening when the problem occurs</summary>

It appears that part of the reason the issue can come and go is because even the order in which the playback commands come into our `MediaSessionManager` can change from one triple/double tap to the next. For example, I added [a bunch of logs](https://gist.github.com/mchowning/956c79471708ba2501226ec505d584a7) to the media session events (before the changes from this PR), and when the skip backward worked fine the logs consistently showed:

```
16:20:20.044  I  TEST123, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_PAUSE, ... }
16:20:20.045  I  TEST123, onPause
16:20:20.068  I  TEST123, KeyEvent { action=ACTION_UP, keyCode=KEYCODE_MEDIA_PAUSE, ... }
16:20:20.545  I  TEST123, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_PREVIOUS, ... }
16:20:20.546  I  TEST123, KeyEvent { action=ACTION_UP, keyCode=KEYCODE_MEDIA_PLAY, ... }
16:20:20.546  I  TEST123, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_PLAY, ... }
16:20:20.549  I  TEST123, onPlay
16:20:20.556  I  TEST123, KeyEvent { action=ACTION_UP, keyCode=KEYCODE_MEDIA_PREVIOUS, ... }
16:20:20.556  I  TEST123, handleMediaButtonTripleTap
16:20:20.559  I  TEST123, onSkipToPrevious
```

When the skip backward did not occur, however, the logs consistently showed a different order of events:

```
16:21:03.836  I  TEST123, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_PAUSE, ... }
16:21:03.836  I  TEST123, onPause
16:21:03.848  I  TEST123, KeyEvent { action=ACTION_UP, keyCode=KEYCODE_MEDIA_PAUSE, ... }
16:21:04.395  I  TEST123, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_PREVIOUS, ... }
16:21:04.396  I  TEST123, KeyEvent { action=ACTION_UP, keyCode=KEYCODE_MEDIA_PREVIOUS, ... }
16:21:04.396  I  TEST123, handleMediaButtonTripleTap
16:21:04.398  I  TEST123, onSkipToPrevious
16:21:04.405  I  TEST123, KeyEvent { action=ACTION_UP, keyCode=KEYCODE_MEDIA_PLAY, ... }
16:21:04.405  I  TEST123, KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MEDIA_PLAY, ... }
16:21:04.407  I  TEST123, onPlay
```

I observed a very similar pattern with the skip forward action as well. With the changes in this PR, though, the skip works successfully no matter which of the (apparently two possible) orders the events come in.

</details>

> [!Note]
> I have this PR targeting the `release/7.54` branch because I think this deserves a beta fix. Given how hard this is to test, I don't think it makes sense to do a hotfix at this point. But, we have beta users confirm that this fixes the issue and we continue to get complaints from production users about the issue, I think that a hotfix might make sense in the future.

### 1. Addresses #1578 with pixel buds
1. Connect a pair of Pixel Buds with the Google Assistant active (i.e., long-pressing on the headset button activates the Google Assistant). These can be either usb-c pixel earbuds (that's what I have) or Bluetooth pixel earbuds (that's what most of our users complaining of the issue have)
2. Confirm that your "Headphone controls" settings in the app have the previous action as "Skip back" and the next action as "Skip forward"
3. Begin playing an episode
4. Verify that using a single-tap on the earbuds pauses/starts playback
5. Verify that double-tapping on the earbuds causes playback to skip forward
6. Verify that triple-tapping on the earbuds causes playback to skip backward
7. Change your "Headphone controls" settings to perform different actions (i.e., skip forward, skip back, add bookmark) and confirm that the headphone controls respond according to that setting value

### 2. Regular Bluetooth speakers/headphones still work as expected
1. Connect a Bluetooth speaker or non-pixel Bluetooth headphones
2. Try the different "Headphone controls" settings and confirm that playback responds appropriately based on that setting (i.e., double tapping does the selected "next action" and triple-tapping does the selected "previous action")

## Checklist
- [x] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [X] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [X] I have considered whether it makes sense to add tests for my changes
- [X] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [X] Any jetpack compose components I added or changed are covered by compose previews

### CODE REVIEW

File: modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt [hunk 1]
```diff
@@ -124,6 +145,14 @@ class MediaSessionManager(
         )
 
         connect()
+
+        @OptIn(DelicateCoroutinesApi::class)
+        GlobalScope.launch {
```
Comment (mchowning) [inline modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt:150]: My initial intention was to avoid using GlobalScope here thanks to the changes in https://github.com/Automattic/pocket-casts-android/pull/1619, but when I decided to have this PR target the release branch I dropped that plan because I do not think we want to add the changes in https://github.com/Automattic/pocket-casts-android/pull/1619 to the release branch. We can just update this usage of Global Scope to use the applicationScope from https://github.com/Automattic/pocket-casts-android/pull/1619 after we merge these changes to `main`.

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/41">7.54 ❄️</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt [hunk 2]
```diff
@@ -124,6 +145,14 @@ class MediaSessionManager(
...
+            commandQueue.collect { (tag, command) ->
+                LogBuffer.i(LogBuffer.TAG_PLAYBACK, "Executing queued command: $tag")
```
Comment (ashiagr) [inline modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt:152]: Good thinking to add these logs 👍

**Review by ashiagr — APPROVED** [review]
Your changes look logical to me. It's also nice that you've added the log statements, so that we know what's happening in the worst case.

The fact that https://github.com/Automattic/pocket-casts-android/pull/1510 was added in 7.52 kind of explains why it's happening more often since then.

**Comment by mchowning** [comment]
Just wanted to note that the skip commands on Pixel Buds will not work even with this fix if they are having [this issue](https://github.com/Automattic/pocket-casts-android/issues/1628) where the Pixel Buds fail to resume playback.

**Comment by bgiesing** [comment]
> This issue does not appear to occur with regular Bluetooth headphones/speakers in my testing.

It happens to me on my Sony WH-1000XM4 over-ear headphones, also with Google Assistant enabled, and still happens even after 7.54-rc-3 which this supposedly fixes for Pixel Buds.

**Comment by mchowning** [comment]
Thanks for that info @bgiesing ! 🙇 

> Play/Pause, Skip Back, and Skip Forward all do not work with Google Assistant enabled, disabling Assistant makes them work again

If Play/Pause aren't working, then that's definitely a different issue that this PR doesn't address. I've opened a couple of other issues about outstanding issues with Pixel Buds, but it sounds like yours might be different from them. If so, it would be great if you could open a new issue.

* https://github.com/Automattic/pocket-casts-android/issues/1624
* https://github.com/Automattic/pocket-casts-android/issues/1628

When you're having this issue, does the play/pause/skip work with any other audio apps, i.e., does it stop working with all apps or only Pocket Casts?

**Comment by bgiesing** [comment]
@mchowning only with Pocket Casts on Android 14 on a Pixel 6a, every other headphone I own (including my Pixel Buds A-Series having Google Assistant also enabled before and after the fix despite others reporting it not working) work fine on both previous and current versions. All my headphones including the Sony's work just fine in every other app like Spotify.

**Comment by CookieyedCodes** [comment]
I also have these headphones & I thought it was related to headset mode vs headphones mode due to if I have a second device skip forward & back work 🤔 🤔 (I haven't not disabled google assistant)

**Comment by SourceOneDocTest** [comment]
Having the same issues with wired Pixel buds on Pixel 5 with assistant enabled. Tried with two separate music playback apps.

Anecdotally it seems to start happening if I also have my phone setup to unlock Chromebook and have access to apps etc in hub. 

If I then disable headset based assistant the music controls work properly again. 

Hoping for a better fix soon - happy to beta test
