### PR TITLE
Track `up_next_shown ` when tapping on navigation bar

### LINKED ISSUE #2363: [Up Next] - `up_next_shown` track event not fired when tap on up next bottom navigation
### Description

Currently we have this event

up_next_shown | When the up next view is displayed to the user | Android- source: [String] [mini_player, now_playing, player, up_next_shortcut] - The name of the view that is displaying the up next view
-- | -- | --

But this one is not being fired when taps on Up Next from bottom navigation

**Expected behavior**: We need to track this event only once like we are doing for Discover tab
- See: p1718725092247959-slack-C06EHRAPW12
- See: https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?gid=0#gid=0&range=A246

### Step-by-step reproduction instructions

Tap on Up Next from bottom navigation bar and see that `up_next_shown` does not fire this event

### Screenshots or screen recording

_No response_

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

_No response_

### PR DESCRIPTION
**Pull request by mebarbosa**
## Description
- This PR fires `up_next_shown` event with `tab_bar` source when tapping on navigation bar 
- NOTE: Both discover and up next navigation bar button should trigger these `up_next_shown` and `discover_shown` events once, but due the opened issue we have https://github.com/Automattic/pocket-casts-android/issues/2149 we are recreating the fragment every time we tap on navigation bar so the event will be fired every time the navigation is tapped

Fixes #2363

## Testing Instructions
1. Open the app
2. Tap on Up Next bottom navigation bar button
3. ✅ Ensure `🔵 Tracked: up_next_shown, Properties: {"source":"tab_bar"` is tracked

## Checklist
- [x] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [x] Any jetpack compose components I added or changed are covered by compose previews
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

File: modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt [hunk 1]
```diff
@@ -190,6 +190,9 @@ class UpNextFragment : BaseFragment(), UpNextListener, UpNextTouchCallback.ItemT
         val binding = FragmentUpnextBinding.inflate(themedInflater, container, false).also {
             realBinding = it
         }
+        if (upNextSource == UpNextSource.UP_NEXT_TAB) {
```
Comment (mebarbosa) [inline modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt:193]: I added this check because I noticed that when we open the up next from another place that is not navigation bar this event is also tracked.

**Review by ashiagr — APPROVED** [review]
