### PR TITLE
Do not set alpha and max lines via reflection

### LINKED ISSUE #2096: Medium & large widgets not loading
### Description

Adding a medium or large widget doesn't work. When currently adding they state "Can't load widget". Tested on both the OnePlus Launcher and Nova Launcher.

### Step-by-step reproduction instructions

1. Add medium or large widget
2. The widget shows Can't load widget

### Screenshots or screen recording

Screenshot_20240422-143252

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

OnePlus 5T
Android 10
Pocket Casts 7.62-rc-3 (9216)

### PR DESCRIPTION
**Pull request by MiSikora**
## Description

Setting alpha on some OEMs via reflection is broken and it results in failures to render widgets. I had to crate a tower of `if/else` statements that selects appropriate layouts based on conditions instead.

On the bright side, now that it is fixed we can safely migrate old widget to Glance.

Widget does not have rounded corners because it is not supported programmatically. We'd need to set a background drawable with rounded corners through XML interoperability. I might do this as a separate enhancement.

Closes #2096

### Bug fix

It's hard to replicate without having a device that failed rendering widgets in the first place. I tested it with One Plus 7T Pro, SDK 30.

1. Add medium and large widgets to your home screen.
2. They should render correctly.

### Regressions

Test widgets with different themes on your regular device.

## Screenshots or Screencast 

| Before | After |
| - | - |
| Screenshot_20240425-175417 | Screenshot_20240425-184616 |

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

File: modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt [hunk 1]
```diff
@@ -1355,11 +1356,24 @@ class SettingsImpl @Inject constructor(
...
-        defaultValue = false,
         sharedPrefs = sharedPreferences,
-    )
+    ) {
+        override fun get(): Boolean {
+            return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
+                sharedPrefs.getBoolean(sharedPrefKey, false)
+            } else {
+                false
+            }
```
Comment (MiSikora) [inline modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt:1368]: I had to do this because if we synced between Android SDK 31 device that had this setting enabled the colors looked of on the device that didn't support dynamic colors.

**Review by mebarbosa — APPROVED** [review]
It worked as expected!
