### PR TITLE
Decrease hide sensitivity of Player's bottom sheet

### LINKED ISSUE #3803: The full screen collapses to a small bar too easily
### Description

When using pocketCasts to version 7.84. In Android 15 on my pixel 7 but on other phones as well the full screen collapses to a small bar too easily with one minor mistaken press
I suggest a lock icon that will allow us to maintain a full screen unless it's released
Thanks for listening

### Step-by-step reproduction instructions

Opening a full screen play, start listening then press anywhere almost and it collapses to a little bar at the bottom

### Screenshots or screen recording

_No response_

### Did you search for existing bug reports?

- [x] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

_No response_

### PR DESCRIPTION
**Pull request by MiSikora**
## Description

This PR adds pre-fling callback interception so we can control whether the sheet should be allowed to collapse or not.

Fixes #3803

## Testing Instructions

1. Open the player.
2. Notice that small fling gestures no longer collapse it.

## Checklist
- [x] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] ~I have considered whether it makes sense to add tests for my changes~
- [ ] ~All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`~
- [ ] ~Any jetpack compose components I added or changed are covered by compose previews~
- [ ] ~I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.~

### CODE REVIEW

File: modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerBottomSheet.kt [hunk 1]
```diff
@@ -217,6 +223,22 @@ class PlayerBottomSheet @JvmOverloads constructor(context: Context, attrs: Attri
...
 
+    private fun createPreFlingInterceptor(
+        behavior: BottomSheetBehavior<*>,
+    ) = object : PreFlingInterceptor {
+        override fun shouldInterceptFlingGesture(velocityX: Float, velocityY: Float): Boolean {
+            return velocityY in -4000f..0f
+        }
+
+        override fun onFlingIntercepted(velocityX: Float, velocityY: Float) {
+            behavior.state = if (velocityY >= 0f) {
```
Comment (MiSikora) [inline modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerBottomSheet.kt:234]:
```suggestion
            behavior.state = if (velocityY > 0f) {
```

File: modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerBottomSheet.kt [hunk 2]
```diff
@@ -96,6 +98,10 @@ class PlayerBottomSheet @JvmOverloads constructor(context: Context, attrs: Attri
         sheetBehavior = BottomSheetBehavior.from(this).apply {
             val callback = createBottomSheetCallback(rootView = parent as CoordinatorLayout)
             addBottomSheetCallback(callback)
+
+            val preFlingInterceptor = createPreFlingInterceptor(behavior = this as ViewPager2AwareBottomSheetBehavior)
```
Comment (sztomek) [inline modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerBottomSheet.kt:102]: 💡 cast is not necessery here, but for the `setPreflingInterceptor` call:

File: modules/services/views/src/main/java/com/google/android/material/bottomsheet/ViewPager2AwareBottomSheetBehavior.kt [hunk 3]
```diff
@@ -20,6 +21,22 @@ open class ViewPager2AwareBottomSheetBehavior<V : View> @JvmOverloads constructo
...
+    }
+
+    override fun onNestedPreFling(coordinatorLayout: CoordinatorLayout, child: V, target: View, velocityX: Float, velocityY: Float): Boolean {
+        val shouldDisableFling = preFlingInterceptor?.shouldInterceptFlingGesture(velocityX, velocityY) ?: false
+        if (shouldDisableFling) {
+            preFlingInterceptor?.onFlingIntercepted(velocityX, velocityY)
+            return false
+        } else {
+            return super.onNestedPreFling(coordinatorLayout, child, target, velocityX, velocityY)
+        }
```
Comment (MiSikora) [inline modules/services/views/src/main/java/com/google/android/material/bottomsheet/ViewPager2AwareBottomSheetBehavior.kt:37]:
```suggestion
        return if (shouldDisableFling) {
            preFlingInterceptor?.onFlingIntercepted(velocityX, velocityY)
            false
        } else {
            super.onNestedPreFling(coordinatorLayout, child, target, velocityX, velocityY)
        }
```

File: modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerBottomSheet.kt [hunk 4]
```diff
@@ -217,6 +223,22 @@ class PlayerBottomSheet @JvmOverloads constructor(context: Context, attrs: Attri
         }
     }
 
+    private fun createPreFlingInterceptor(
+        behavior: BottomSheetBehavior<*>,
+    ) = object : PreFlingInterceptor {
+        override fun shouldInterceptFlingGesture(velocityX: Float, velocityY: Float): Boolean {
+            return velocityY in -4000f..0f
```
Comment (sztomek) [inline modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerBottomSheet.kt:230]: ❓ just wondering how you came up with this arbitrary number? Was it a trial-and-error method?

File: modules/services/views/src/main/java/com/google/android/material/bottomsheet/ViewPager2AwareBottomSheetBehavior.kt [hunk 5]
```diff
@@ -20,6 +21,22 @@ open class ViewPager2AwareBottomSheetBehavior<V : View> @JvmOverloads constructo
...
 ) : BottomSheetBehavior<V>(context, attrs) {
+    private var preFlingInterceptor: PreFlingInterceptor? = null
+
+    fun setPreFlingInterceptor(interceptor: PreFlingInterceptor) {
+        preFlingInterceptor = interceptor
+    }
+
+    override fun onNestedPreFling(coordinatorLayout: CoordinatorLayout, child: V, target: View, velocityX: Float, velocityY: Float): Boolean {
+        val shouldDisableFling = preFlingInterceptor?.shouldInterceptFlingGesture(velocityX, velocityY) ?: false
+        if (shouldDisableFling) {
```
Comment (sztomek) [inline modules/services/views/src/main/java/com/google/android/material/bottomsheet/ViewPager2AwareBottomSheetBehavior.kt]: 💡 `return` could be hoisted to the `if` statement:
` return if (shouldDisableFling) {  ... false } else { super.onNested... }`

**Review by sztomek — APPROVED** [review]
Nice improvement on the fling sensitivity!

💡 Maybe we should also consider a dismiss threshold for the y offset (e.g. if the user slowly swipes 1/3 or 1/2 of the screen height), because currently if you swipe slow enough, you can drag the bottom sheet to the very bottom of the screen, and it will bounce back to expanded state upon release:

https://github.com/user-attachments/assets/5a989d2a-8e61-4270-a2cc-b7fe6d094e9a
