### PR TITLE
Fix/issue 1192 toolbar disappear on add file screen

### LINKED ISSUE #1192: Top navigation bar and podcast art disappears on orientation change
### Description

When you are on the final screen to add a personal file, if you change the screen orientation, the top navigation bar and the podcast artwork disappear. You are unable to click the back button and/or save button, leaving the user stuck on the screen unless using the phone's navigation buttons/gestures.

### Step-by-step reproduction instructions

1. Go to the user account page.
2. Click on the Files button.
3. Click the Add button (Floating Action Button).
4. Select a file to upload.
5. You will automatically be taken to the Add File screen.
6. Change the orientation of the screen/phone.

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/68164093/b7767dd7-6f25-43f3-9f08-e5e71881265f

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 6 on API 33. Pocket Casts version 7.43.

### PR DESCRIPTION
**Pull request by P-Burk**
## Description

This PR is to fix a bug on the *Add File* Activity/Screen where when a user has a file selected for upload and changes the screen orientation the Toolbar does not load and the file art disappears. When this occurs, the save and back navigation buttons within the Toolbar also do not work as they are not loaded.

Fixes #1192

## Testing Instructions

1. Go to the user account page.
2. Click on the Files button.
3. Click the Add button (Floating Action Button).
4. Select a file to upload.
5. You will automatically be taken to the Add File screen.
6. Change the orientation of the screen/phone and the Toolbar + file art should reappear when the Activity is recreated.

#### Before:
Check the original issue for a Before screen cap of the issue.
#### After:
https://github.com/Automattic/pocket-casts-android/assets/68164093/ea22d2e1-d867-4eae-baad-ffd8ac3e77b0

## Checklist
- [x] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
	- No strings added.
- [ ] Any jetpack compose components I added or changed are covered by compose previews
	- No Jetpack compose components added or changed.
 
#### I have tested any UI changes...

- [x] with different themes
- [x] with a landscape orientation
- [x] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack
	- This was a bug fix to bring back a missing UI element

#### Notes:
`savedInstanceState.getParcelable(key: String)` is deprecated. I did have a solution to fix this, which involves using `savedInstanceState.getParcelable(key: String, clazz: Class<T>)`, but it requires Android version 33 and the minimum SDK version is 23. So for the time being, I suppressed the deprecation warning because I saw the same suppression used elsewhere in the `AddFileActivity.kt` file (where my changes take place).
image

### CODE REVIEW

**Review by geekygecko — COMMENTED** [review]
Thanks for fixing this issue, it worked well for me. Is there a reason the constant value is "null" and not something like "DATAURI"?

**Comment by P-Burk** [comment]
> Thanks for fixing this issue, it worked well for me. Is there a reason the constant value is "null" and not something like "DATAURI"?

To be 100% honest, no reason other than I'm new to this (OSS contributions) and Kotlin. I'm not sure what the "default" values should be for constants.

File: modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/AddFileActivity.kt [hunk 1]
```diff
@@ -83,6 +83,7 @@ private const val ACTION_PICK_FILE = 2
 private const val EXTRA_EXISTING_EPISODE_UUID = "fileUUID"
 private const val EXTRA_FILE_CHOOSER = "filechooser"
 private const val STATE_LAUNCHED_FILE_CHOOSER = "LAUNCHED_FILE_CHOOSER"
+private const val STATE_DATAURI = "null"
```
Comment (geekygecko) [inline modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/AddFileActivity.kt:86]:
```suggestion
private const val STATE_DATAURI = "DATAURI"
```
Can we change it to this? It just needs to be unique from the other state constants and null looks like we forgot to add a value.

**Review by geekygecko — APPROVED** [review]
