### PR TITLE
Fix: Track `discover_featured_page_changed` event only when Discover is visible

### LINKED ISSUE #2379: [Discover] Fix - `discover_featured_page_changed` event is tracked even if the discover page is not visible
### Description

When we first launch the app the `discover_featured_page_changed` is tracked even if the screen is not visible. 

See: p1718795716620289/1718795055.315149-slack-C028JAG44VD

### Step-by-step reproduction instructions

1. Install the app
2. Observe that Discover page will be override and the Sign in / Log in page will be displayed
3. ❌ See that `discover_featured_page_changed` continues firing even if the discover page is not visible 

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/42220351/b3b50b71-5f19-493f-91a6-f0e2a6e4934e

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

_No response_

### PR DESCRIPTION
**Pull request by mebarbosa**
## Description
- `discover_featured_page_changed` track event was being tracked even if the screen was not visible
- See: p1718795716620289/1718795055.315149-slack-C028JAG44VD

Fixes #2379

## Testing Instructions
1. Remove any already installed pocket casts app to have a fresh install
2. Install the app from this branch 
3. ✅ When you see the Log in / Sign in screen, ensure `discover_featured_page_changed` does not continue firing
4. Close the Log in / Sign in screen
5. Go to Discover
6.  ✅ Ensure `discover_featured_page_changed` is tracked
7. Go to another screen
8.  ✅ Ensure `discover_featured_page_changed` is not tracked

## Checklist
- [x] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] I have considered whether it makes sense to add tests for my changes
- [x] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [x] Any jetpack compose components I added or changed are covered by compose previews
- [x] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.
 
#### I have tested any UI changes...

- [x] with different themes
- [x] with a landscape orientation
- [x] with the device set to have a large display and font size
- [x] for accessibility with TalkBack

### CODE REVIEW

File: modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt [hunk 1]
```diff
@@ -136,10 +136,17 @@ internal class DiscoverAdapter(
     }
     var onChangeRegion: (() -> Unit)? = null
 
+    private var isDiscoverVisible = true
```
Comment (MiSikora) [inline modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt:139]: I think that this property name is a bit misleading. Something like `isFeaturePageTrackingEnabled` is more explicit and accurate.

File: modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt [hunk 2]
```diff
@@ -136,10 +136,17 @@ internal class DiscoverAdapter(
...
+
     private val imageRequestFactory = PocketCastsImageRequestFactory(context).smallSize().themed()
 
     init {
         setHasStableIds(true)
+        isDiscoverVisible = true
```
Comment (MiSikora) [inline modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt:145]: There is no need to set it to `true` in `init` block since it is the default value of the property.

File: modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt (hunk 1 above)
Comment (mebarbosa) [reply modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt]: I agree! I've pushed the changes

**Review by MiSikora — APPROVED** [review]

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/pocket-casts-android/milestone/56">7.67</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>
