### PR TITLE
Dispatch refresh state when refresh task is throttled

### LINKED ISSUE #2153: The podcasts are taking too long to load when refreshing the Podcasts tab
### Description

We're experiencing infinite loading when refreshing podcasts in the Podcasts tab. I was only able to reproduce this issue after adding cloud files (videos) to my account, and I had around 100 podcast subscriptions.

I can't reproduce this consistently every time.

### Step-by-step reproduction instructions

1. Have an account with around 100 podcast subscriptions and some cloud videos uploaded to the account
2. Run the app
3. Go to Podcasts tab
4. Refresh the podcast list
5. The first refresh should work as expected
6. After finishes the refresh, try to refresh it again
7. ❌ You will notice the refresh gets stuck or takes loo long to finish

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/42220351/493cc360-c69e-4331-9574-0d4c976a8876

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Pocket Casts `7.63-rc-3`

### PR DESCRIPTION
**Pull request by MiSikora**
## Description

This PR addresses an issue with our manual refresh task, which implements a 15-second throttle in pull-to-refresh scenarios. Previously, we did not dispatch a "refreshed" state upon task completion due to this throttling mechanism. Additionally, throttling is disabled in debug builds, rendering this bug non-reproducible in those environments.

I have prepared a patch that enables throttling in debug builds to facilitate testing of this fix.
Closes #2153

## Testing Instructions

1. Apply [this patch](https://github.com/Automattic/pocket-casts-android/files/15219568/refresh.patch).
2. Install the app.
3. Go to the podcasts tab.
4. Pull to refresh and wait for the sync to finish.
5. Pull to refresh again.
6. Spinner should disappear.

## Checklist
- [x] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [x] ~I have considered whether it makes sense to add tests for my changes~
- [x] ~All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`~
- [x] ~Any jetpack compose components I added or changed are covered by compose previews~
- [x] ~I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.~
 
#### I have tested any UI changes...

- [x] ~with different themes~
- [x] ~with a landscape orientation~
- [x] ~with the device set to have a large display and font size~
- [x] ~for accessibility with TalkBack~

### CODE REVIEW

File: modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsTask.kt [hunk 1]
```diff
@@ -103,9 +103,6 @@ class RefreshPodcastsTask @AssistedInject constructor(
                     applicationScope = applicationScope,
                     runNow = true,
                 )
-                if (!refreshThread.isAllowedToRun(runNow = true)) {
-                    return@withContext
-                }
```
Comment (MiSikora) [inline modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsTask.kt:108]: This isn't needed here as `RefreshPodcastsThread` already handles this scenario.

File: modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt [hunk 2]
```diff
@@ -270,6 +273,11 @@ class RefreshPodcastsThread(
         getEntryPoint().settings().setRefreshState(RefreshState.Failed(message))
     }
 
+    private fun dispatchCurrentRefreshedState() {
+        val settings = getEntryPoint().settings()
+        (settings.getLastSuccessRefreshState() ?: RefreshState.Never).let(settings::setRefreshState)
```
Comment (MiSikora) [inline modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt:278]: There is an edge case where we lose failure state due to this but I don't see any way around it without rewriting a lot of code. I think this is an acceptable compromise.

File: modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt [hunk 3]
```diff
@@ -364,8 +372,8 @@ class RefreshPodcastsThread(
 
         private const val GROUP_NEW_EPISODES = "group_new_episodes"
 
-        private val THROTTLE_RUN_NOW_MS: Long = if (BuildConfig.DEBUG) 0 else 15000 // 15 seconds
-        private val THROTTLE_PERIODIC_MS: Long = if (BuildConfig.DEBUG) 0 else 5L * 60L * 1000L // 5 minutes
+        private val THROTTLE_RUN_NOW_MS: Long = if (BuildConfig.DEBUG) 0 else 15.seconds.inWholeMilliseconds
+        private val THROTTLE_PERIODIC_MS: Long = if (BuildConfig.DEBUG) 0 else 5.minutes.inWholeMilliseconds
```
Comment (geekygecko) [inline modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt:376]: I will try to do this in the future. It's so much cleaner.

**Review by geekygecko — APPROVED** [review]
Great, that worked well in testing.

File: modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt (hunk 2 above)
[the remark this answers is not in the document]
Comment (MiSikora) [reply modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt:278]: No, not really. I like your version better. 👍
