### PR TITLE
Do not scroll episode artwork settings app bar

### LINKED ISSUE #3567: Episode Artwork settings have scrollable app bar
### Description

After Android 15 migration the Episode Artwork page top bar is scrollable which can lead to content being obstructed by the status bar icons or camera hole.

### Step-by-step reproduction instructions

1. Increase font size so that Episode Artwork screen doesn't fit in a single screen.
2. Go to the settings.
3. Go to the Appearance page.
4. Go to the Advanced episode artwork.
5. Scroll content.
6. Notice that the the app bar scrolls with the content.

### Screenshots or screen recording

https://github.com/user-attachments/assets/d8c9ed2b-cc8e-44b2-bc8b-b99920b7fa70

### Did you search for existing bug reports?

- [x] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 6, Android 15,d921898d660ddb1abf90639e38dd1b9176490cf6

### PR DESCRIPTION
**Pull request by MiSikora**
## Description

Episode Artwork settings app bar was scrollable making it inaccessible when scrolled up and hidden behind notification status bar.

Fixes #3567

## Testing Instructions

1. Increase font size so that Episode Artwork screen doesn't fit in a single screen.
2. Go to the settings.
3. Go to the Appearance page.
4. Go to the Advanced episode artwork.
5. Scroll content.
6. Notice that the the app bar does not scroll with the content.

## Checklist
- [ ] ~If this is a user-facing change, I have added an entry in CHANGELOG.md~
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] ~I have considered whether it makes sense to add tests for my changes~
- [ ] ~All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`~
- [ ] ~Any jetpack compose components I added or changed are covered by compose previews~
- [ ] ~I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.~
 
#### I have tested any UI changes...

- [x] with different themes
- [x] with a landscape orientation
- [x] with the device set to have a large display and font size
- [ ] ~for accessibility with TalkBack~

### CODE REVIEW

File: modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/EpisodeArtworkConfigurationFragment.kt [hunk 1]
```diff
@@ -83,30 +83,32 @@ class EpisodeArtworkConfigurationFragment : BaseFragment() {
...
+                    heading = stringResource(LR.string.settings_use_episode_artwork_customization_section),
+                    subHeading = stringResource(LR.string.settings_use_episode_artwork_customization_description),
+                    showDivider = false,
+                ) {
+                    elements.forEach { element ->
+                        ArtworkElement(artworkConfiguration, element, onUpdateConfiguration)
+                    }
                 }
+                Spacer(
+                    modifier = Modifier.height(dimensionResource(UR.dimen.mini_player_height)),
```
Comment (geekygecko) [inline modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/EpisodeArtworkConfigurationFragment.kt:109]: In other parts of the app, I have seen the following used to accommodate the mini player height. 
```
val bottomInset = settings.bottomInset.collectAsStateWithLifecycle(0)
...
modifier = Modifier.height(bottomInset.value.pxToDp(LocalContext.current).dp),
```

**Review by geekygecko — APPROVED** [review]
