### PR TITLE
Warn when changing to metered network if setting is enabled

### LINKED ISSUE #1374: Switches to streaming on metered connection without data warning
### Description

If you start streaming an episode on wifi, and switch to a metered connection in the middle of the episode, the episode will continue playing without giving any warning even if you have turned on the setting to warn before streaming an episode. That warning will only get shown when you start playback.

This is a problem for users who do not want to use metered data.

Reported in 6813856-zd-a8c.

### Step-by-step reproduction instructions

1. Turn on the setting to warn when streaming an episode.
2. Connect to wifi and a metered connection
3. Start streaming an episode
4. Disconnect from wifi
5. ❗  Observe that the episode continues playing, even if you skip to a part of the episode that is far in the future (and therefore wasn't buffered when on wifi)
6. Pause the episode
7. Tap play to resume the episode
8. Observe that the stream warning is now presented

### Screenshots or screen recording

_No response_

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Android Pixel 6 Pro, Android 13, Pocket Casts 7.46.2

### PR DESCRIPTION
**Pull request by mchowning**
## Description

For users who have enabled the "Warn before using data" setting, we would check if a metered connection was being used when an episode started playing, but we would not do anything if, during playback, the user switched from an unmetered connection to a metered connection. This PR addresses that by detecting when the app has switched to a metered connection, and then pausing playback and presenting the user with a notification asking if they would like to continue playback.

We are only presenting this warning once when an episode is played. This means that if a user gets a warning when they start playing an episode, and they choose to stream it, then we will not present any later warnings if their network switches back and forth between metered networks. Likewise, if a user switches between metered and unmetered networks multiple times, we will only display the warning once per episode.

Fixes #1374
h/t to @neeldoshii for helping inspire this solution with https://github.com/Automattic/pocket-casts-android/pull/1447

These changes should not affect the watch or automotive apps because the warn before streaming setting defaults to false and cannot be changed within those apps. This is something we'll need to consider when we start syncing settings though.

## Testing Instructions

For all of these tests:
1. Install a build from this PR
3. Make sure you have two networks available: one that is treated as unmetered and one that is treated as metered.

### 1. Warns one time per episode when switching to metered network
2. Turn the setting for "Warn before using data" under "Storage & data use" to be on
1. Connect to an unmetered network
2. Begin streaming an episode
3. ✅  Verify that you do NOT get a stream warning
4. Switch to a metered network
5. ✅  Verify that you do get a stream warning and playback pauses
6. Tap the notification button to continue streaming ("Yes, keep playing")
7. ✅ Verify that playback continues
8. Switch to your unmetered network
9. Switch back to your metered network
10. ✅ Verify that you are NOT presented with a second stream warning
11. Begin streaming a different episde
12. ✅ Verify that you are shown a stream warning (whether you get a system notification or a bottom sheet depends on where you start playback from within the app and is not affected by the changes in this PR)
13. Tap the button to continue playing the episode
5. Switch to an unmetered network
6. Switch back to your metered network
7. ✅ Verify that you are NOT presented with a stream warning

### 2. Play next downloaded button works as before
2. Turn the setting for "Warn before using data" under "Storage & data use" to be on
1. Add a few episodes that are not downloaded to your queue
1. Add a downloaded episode to the middle of your queue
2. Take note of the top downloaded episode in your queue (it should not be at the top of your queue though)
1. Connect to an unmetered network
1. Begin streaming an episode
1. Switch to a metered network
1. ✅ Verify that you are shown a stream warning and playback pauses
1. Tap the "Play next downloaded" notification button
3. Verify that the episode that was previously the highest downloaded episode in your queue has started playing.

### 3. Does not show stream warning for downloaded episodes
2. Turn the setting for "Warn before using data" under "Storage & data use" to be on
2. Connect to an unmetered network
3. Download an episode
5. Begin playing that episode
6. Switch to a metered connection
8. ✅ Verify that you are NOT shown a stream warning

### 4. Does not show stream warning if setting is turned off
1. Turn the setting for "Warn before using data" under "Storage & data use" to be OFF
2. Connect to an unmetered network
3. Begin streaming an episode
4. Switch to an unmetered network
5. ✅ Verify that you are NOT shown a stream warning
6. Start streaming a different episode
9. ✅ Verify that playback starts immediately and you are NOT shown a stream warning.

### 5 Does not show stream warning if chromecasting
2. Turn the setting for "Warn before using data" under "Storage & data use" to be on
2. Connect to an unmetered network
3. Begin chromecasting an episode that you have not downloaded
4. Switch your device to a metered connection
5. ✅ Verify that you are NOT shown a stream warning

### 6. Fixes double-warning issue
2. Turn the setting for "Warn before using data" under "Storage & data use" to be on
3. Connect to a metered network
4. Make sure you have some episodes in your up next queue
5. Start playback from your up next queue by long-pressing on one of the items (or if you have the setting turned on for a regular press to start playback instead of opening the episode details screen, do that)
6. Observe that you get a notification asking if you want to stream
7. Proceed to stream the episode
8. Pause the episode from the miniplayer
9. Resume the episode from the miniplayer
10. ✅ Observe that the episode plays and you are not again presented with a notification asking whether you want to stream the episode (before this PR, you would get asked a second time in this flow).

## Screenshots or Screencast 

https://github.com/Automattic/pocket-casts-android/assets/4656348/c355bafb-790e-4ac4-b34a-1be78bf931be

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [X] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [X] I have considered whether it makes sense to add tests for my changes
- [X] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [X] Any jetpack compose components I added or changed are covered by compose previews

### CODE REVIEW

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">No reviewers have been set for this PR yet. Please request a review from <strong>@ Automattic/pocket-casts-android</strong>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">No reviewers have been set for this PR yet. Please request a review from <strong>@ Automattic/pocket-casts-android</strong>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Mukuljangir372** [comment]
Hi @mchowning, There are some issues need attention with your PR. I would like to add some reviews over the PR.

File: modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/NetworkConnectionWatcher.kt [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+    private val networkCallback = object : ConnectivityManager.NetworkCallback() {
+        override fun onCapabilitiesChanged(network: Network, networkCapabilities: NetworkCapabilities) {
+            applicationScope.launch {
+                this@NetworkConnectionWatcher.onCapabilitiesChanged(networkCapabilities)
+            }
+            super.onCapabilitiesChanged(network, networkCapabilities)
+        }
+    }
+
+    fun startWatching() {
```
Comment (Mukuljangir372) [inline modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/NetworkConnectionWatcher.kt:35]: Should we use a cold flow for watching the network connectivity? wdyt?

File: modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt [hunk 2]
```diff
@@ -365,10 +365,28 @@ open class PlaybackManager @Inject constructor(
         return player?.supportsVolumeBoost() ?: false
     }
 
+    suspend fun onSwitchedToMeteredConnection() {
+
```
Comment (Mukuljangir372) [inline modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt:369]: Extra line space:)

**Review by Mukuljangir372 — APPROVED** [review]

File: modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt (hunk 2 above)
Comment (mchowning) [reply modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt:369]: This was actually intentional. I prefer how the extra line space makes the early return easier to see. If there are strong opinions against this though, I can certainly remove it.

File: modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/NetworkConnectionWatcher.kt (hunk 1 above)
Comment (mchowning) [reply modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/NetworkConnectionWatcher.kt:35]: We could do that, but I'm not seeing a lot of benefit to that change at this point. Since this is in one of the higher-level modules, most other classes cannot directly depend on this class (and observe the flow) without us adding a fair bit of DI complexity.

**Comment by pocketcasts** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt (hunk 2 above)
Comment (mchowning) [reply modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt]: Turns out that with our updates to Spotless it also doesn't like the extra space, so it's removed now. 😄

File: modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/NetworkConnectionWatcher.kt (hunk 1 above)
Comment (mchowning) [reply modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/NetworkConnectionWatcher.kt]: I've updated the class monitoring the network status to just expose a flow. I just used a state flow because that seemed more straightforward and the PlaybackManager will be collecting from this flow during the entire life of the application anyway.

File: modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/NetworkConnectionWatcher.kt [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+import dagger.hilt.android.qualifiers.ApplicationContext
+import kotlinx.coroutines.CoroutineScope
+import kotlinx.coroutines.launch
+import javax.inject.Inject
+import au.com.shiftyjelly.pocketcasts.utils.Network as PCNetworkUtils
+
+class NetworkConnectionWatcher @Inject constructor(
+    @ApplicationScope private val applicationScope: CoroutineScope,
+    @ApplicationContext private val context: Context,
+    private val playbackManager: PlaybackManager,
```
[the remark this answers is not in the document]
Comment (mchowning) [reply modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/NetworkConnectionWatcher.kt]: I initially did it this way to just keep the changes to a minimum and not add any undue complexity, but I've gone ahead and extracted out the `PlaybackManager` dependency. I also created a separate class to handle updating the `PlaybackManager` based on network changes in order to minimize how much code we're adding to the already-very-large `PlaybackManager` class.

[the remark this answers is not in the document]
Comment (Mukuljangir372) [reply modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/NetworkConnectionWatcher.kt]: It makes sense.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by ashiagr — APPROVED** [review]
Thanks so much for this effort! I found everything working as described.
