### PR TITLE
Fix: OPML Import

### LINKED ISSUE #1716: OPML Import: Show an error when importing fails
### Description

When Importing an OPML file, no error message is shown despite the import failing. 

### Step-by-step reproduction instructions

1. Import an OPML file such as the one shared here (Internal Link: p1705580029359379/1705580020.681289-slack-C02A333D8LQ)
2. Notice you get a message that the import has started, but nothing happens

### Screenshots or screen recording

The only message shown: 
image

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung Z Fold 4, Android 13, Pocket Casts 7.55 rc-2 (9184)

### LINKED ISSUE #2259: Can't import OPML files from Google Podcasts
### Description

This is caused because Google Podcast app is generating an OPML file with invalid XML characters 
See: (Internal Link: p1705580029359379/1705580020.681289-slack-C02A333D8LQ

### Step-by-step reproduction instructions

Try to import an OPML file attached on the internal ref and see that you can't import the podcasts

### Screenshots or screen recording

_No response_

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

_No response_

### PR DESCRIPTION
**Pull request by mebarbosa**
## Description
- This PR addresses two issues. The first one is that we were not displaying any message error when we try to import a invalid OPML file and the other issue is that we were not able to import OPML from Google Podcast app. This is because Google was not removing invalid xml characters so we could not parse the file
- See Internal Link: p1705580029359379/1705580020.681289-slack-C02A333D8LQ)

Closes #1716
Closes #2259 

## Testing Instructions
1. Download the file p1705580029359379/1705580020.681289-slack-C02A333D8LQ
2. In your device files, tap on this OPML file and import to Pocket Casts (You can tap on share button and select Pocket Casts app)
3. Go to Podcasts tab
4. ✅ Make sure the podcasts were imported 

## Screenshots or Screencast 

https://github.com/Automattic/pocket-casts-android/assets/42220351/f4320e5e-f225-439c-b224-de76de3dad7a

## Checklist
- [ ] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [x] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
- [ ] I have considered whether it makes sense to add tests for my changes
- [ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [ ] Any jetpack compose components I added or changed are covered by compose previews
- [ ] I have updated (or requested that someone edit) [the spreadsheet](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?usp=sharing) to reflect any new or changed analytics.
 
#### I have tested any UI changes...

- [ ] with different themes
- [ ] with a landscape orientation
- [ ] with the device set to have a large display and font size
- [ ] for accessibility with TalkBack

### CODE REVIEW

File: modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/opml/OpmlImportTask.kt [hunk 1]
```diff
@@ -227,6 +240,27 @@ class OpmlImportTask @AssistedInject constructor(
         processUrls(urls)
         return urls.size
     }
+    private fun replaceInvalidXmlCharacter(inputStream: InputStream): InputStream {
+        val content = inputStream.bufferedReader().use { it.readText() }
```
Comment (MiSikora) [inline modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/opml/OpmlImportTask.kt:244]: This reads the whole input stream to the memory. For large files it will cause OOM.

File: modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/opml/OpmlImportTask.kt [hunk 2]
```diff
@@ -227,6 +240,27 @@ class OpmlImportTask @AssistedInject constructor(
...
+
+        val indentedContent = content.replace("<outline", "\n<outline")
+
+        val modifiedContent = indentedContent
+            .replace("&", "&amp;")
```
Comment (MiSikora) [inline modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/opml/OpmlImportTask.kt:249]: If a file is correctly formatted this breaks it. Imagine that a file has `&amp;` inside of it. It would be changed to `&amp;amp;` or `&gt;` to `&amp;gt;` and so on.

**Review by MiSikora — CHANGES_REQUESTED** [review]

File: modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/opml/OpmlImportTask.kt (hunk 1 above)
Comment (mebarbosa) [reply modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/opml/OpmlImportTask.kt]: [758972f](https://github.com/Automattic/pocket-casts-android/pull/2260/commits/758972fbd3eaf166d2c440c9f17816f29016f8be)

**Review by MiSikora — CHANGES_REQUESTED** [review]
Current import is broken. [Here](https://drive.google.com/file/d/11sUsETeknk1lz8zIzmDvt2eVSqC9AdeG/view?usp=sharing) is a file exported from our app. It contains 4000 podcasts. When importing it on this branch only 5 podcasts are processed.

**Comment by MiSikora** [comment]
Good job! I've tested with different files at it worked. 👍

**Comment by geekygecko** [comment]
Would it be a good idea to add a unit test for this?

**Comment by mebarbosa** [comment]
> Would it be a good idea to add a unit test for this?

@geekygecko Yes! I've added here -> https://github.com/Automattic/pocket-casts-android/pull/2272
